version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dependencies
    container_name: "affine-app"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/web/node_modules
    ports:
      - "${APP_PORT:-3000}:8080"
    restart: unless-stopped
    networks:
      - affinenet
    command: pnpm run dev
    #command: sleep 9999

networks:
  affinenet:
    external: true